# Generated by Django 5.2.3 on 2025-06-26 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0002_alter_channel_server_alter_server_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
